# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50ab25cf8e26951c5f6e71e2f458baf5"
application_url = "https://invalid-inclusion-believed-statistical.trycloudflare.com"
embedded = true
name = "zoho books integration"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://invalid-inclusion-believed-statistical.trycloudflare.com"
]
