# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50ab25cf8e26951c5f6e71e2f458baf5"
name = "zoho books integration"
application_url = "https://achiness-shorthand-vaporizer.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/products"

[[webhooks.subscriptions]]
topics = ["inventory_levels/update"]
uri = "/webhooks/inventory-levels"

[[webhooks.subscriptions]]
topics = ["customers/update"]
uri = "/webhooks/customers"

[[webhooks.subscriptions]]
topics = ["orders/create", "orders/updated"]
uri = "/webhooks/orders"

[[webhooks.subscriptions]]
topics = ["order_transactions/create"]
uri = "/webhooks/order-transactions"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_inventory,write_inventory,read_locations"
optional_scopes = [ ]

[auth]
redirect_urls = [
  "https://achiness-shorthand-vaporizer.ngrok-free.dev/auth/callback"
]
