# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50ab25cf8e26951c5f6e71e2f458baf5"
name = "zoho books integration"
application_url = "https://achiness-shorthand-vaporizer.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/products"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]

[auth]
redirect_urls = [
  "https://achiness-shorthand-vaporizer.ngrok-free.dev/auth/callback"
]
